name: Arxiv Paper Summarizer

on:
  schedule:
    - cron: "0 3 * * *"  # Run daily at 1 AM UTC, or 11 PM EST

jobs:
  summarize:
    runs-on: ubuntu-latest

    env:  # Define environment variables
      GITHUB_TOKEN: ${{ secrets.LLM_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Paper Summarizer, commit, push and create PR
        run: |
          python main.py
